"""Stubbed review pipeline used until LLM integration is available."""

from __future__ import annotations

import hashlib
from typing import Dict, List, Tuple

from app.schemas.review_schemas import ReviewComment


def _infer_primary_file(diff: str) -> str:
    for line in diff.splitlines():
        if line.startswith("+++ b/"):
            return line.replace("+++ b/", "", 1)
        if line.startswith("+++ "):
            return line.replace("+++ ", "", 1)
    return "unknown"


def run_stubbed_review(diff: str | None) -> Tuple[str, List[ReviewComment], Dict[str, object]]:
    metadata = {
        "agents_run": ["stub-agent"],
        "total_comments": 0,
        "files_reviewed": 0,
        "severity_breakdown": {"info": 1},
        "categories_detected": ["logic"],
    }
    if not diff:
        metadata["severity_breakdown"] = {}
        metadata["categories_detected"] = []
        return ("No diff content provided; unable to perform review.", [], metadata)

    file_path = _infer_primary_file(diff)
    checksum = hashlib.sha256(diff.encode("utf-8")).hexdigest()[:8]

    comment = ReviewComment(
        agent="stub-agent",
        file_path=file_path,
        line_number_start=1,
        line_number_end=5,
        category="logic",
        severity="info",
        title="Stubbed recommendation",
        body=(
            "This is a placeholder comment generated by the stub pipeline. "
            "Replace with real multi-agent insights once the LLM integration is wired."
        ),
        suggested_fix="Run the Day 3 pipeline to see real feedback.",
    )

    summary = (
        "Stub review #{checksum} for {file_path}: replace with real LLM-backed comments soon."
    ).format(checksum=checksum, file_path=file_path)

    metadata["total_comments"] = 1
    metadata["files_reviewed"] = 1
    return summary, [comment], metadata
